### ISSUE TITLE
Nadeko Keeps Aborting and Reseting in logs 

### ISSUE THREAD

**Issue by BlazeDraaws** [ScarletKuro/NadekoBot-Heroku-Auto-Deploy#1]
![image](https://user-images.githubusercontent.com/49316600/55896145-e9256780-5bbd-11e9-875e-cb4744fa9e6b.png)
i cloned your repo,edited the images.json file and the font file. i successfully pushed it and deployed it. yet the bot isnt online

**Comment by ScarletKuro** [comment]
Can you log in dashboard.heroku.com, open your app and in the "overview" tab click "Heroku Postgre"(a new tab will open), click settings and "view credentials". Then go on previous tab(dasboard of your app), go on the settings and "reveal config vars" and compare the DATABASE_URL with the URI from Heroku Postgre settings. They should be the same

**Comment by ScarletKuro** [comment]
also, i forgot to mention, if you changing pics, you need to run imagesreload command

**Comment by BlazeDraaws** [comment]
i will take that into consideration 
_next time......_
