### ISSUE TITLE
Error message whenever an user joins and the bot tries to greet them

### ISSUE THREAD

**Issue by letterjm** [ScarletKuro/NadekoBot-Heroku-Auto-Deploy#11]
![image](https://user-images.githubusercontent.com/72457221/97311825-29e5df80-183b-11eb-9691-b967b4bc27c9.png)

I tried restarting the bot or resetting the greet message, but it doesn't work. The greet message also doesn't display anymore.
The rest of the bot works perfectly fine, it's really only the greet message that seems faulty.

How to fix?

**Comment by ScarletKuro** [comment]
Well, discord changed something apparently. Try doing this

Certain Nadeko features require Discord's privileged gateway intents. These include greeting and goodbye messages, as well as creating the Owner message channels for DM forwarding.

To enable privileged gateway intents, head over to the Discord Developer Portal and select your Application. Then, click on "Bot" in the left side navigation panel, and enable both intents. If your bot is in 100 or more servers, you'll need to apply to use the intents with Discord, but for small selfhosts, all that is required is enabling the intents in the developer portal.

After enabling the intents, restart your bot.
![](https://cdn.discordapp.com/attachments/117523346618318850/770638489011486780/Capture.PNG)

**Comment by letterjm** [comment]
Thank you so much, that fixed it!
