### ISSUE TITLE
My bot is not going online

### ISSUE THREAD

**Issue by DeceptionCeption** [ScarletKuro/NadekoBot-Heroku-Auto-Deploy#15]
I followed the tutorial step by step to the letter (both ways- simple way, aka purple button, and the "non simple" way) yet it's still not doing anything even if my build was shown that it was successful in every step. I know that my issue sounds too vague but I can't think of anything which could have led me to this.

**Comment by ScarletKuro** [comment]
Any logs or additional info?

**Comment by ItsJustJoshDev** [comment]
I was wondering how tf do I deploy the bot?? I know it's probably something simple but I need help

**Comment by ScarletKuro** [comment]
Have you tried to read the text below the repository? https://github.com/ScarletKuro/NadekoBot-Heroku-Auto-Deploy
Literally just saying to click the button to automatically deploy it on your heroku account

**Comment by ItsJustJoshDev** [comment]
I deployed it but the bot offline??

**Comment by ItsJustJoshDev** [comment]
@ScarletKuro so is there anything else i may have missed

**Comment by ScarletKuro** [comment]
Well it turned out that this doesn't work on herokus newest stack-20, it was made for stack-16/18, and since I have no time to work on it and fix, I'm going to drop support of nadeko heroku version. So yeah, this won't work from now on.
