### ISSUE TITLE
Music with no titles

### ISSUE THREAD

**Issue by ArgentBlueKitsune** [ScarletKuro/NadekoBot-Heroku-Auto-Deploy#3]
![image](https://user-images.githubusercontent.com/12589062/62808532-57276000-bac6-11e9-85ff-2df6c5e08a89.png)
How can I fix this?

**Comment by Macleykun** [comment]
Try this on the public Nadeko first.

Does it occur? Ask there. Kuro will update sooner or later to it then.
Does it not occur? Wait for Kuro to respond.

Van: katherynliza
Verzonden: vrijdag 9 augustus 2019 22:54
Aan: ScarletKuro/NadekoBot-Heroku-Auto-Deploy
CC: Subscribed
Onderwerp: [ScarletKuro/NadekoBot-Heroku-Auto-Deploy] Music with no titles (#3)


How can I fix this?

**Comment by ArgentBlueKitsune** [comment]
Do you mean nadeko discord? Also there alot of Kuros on their discord

**Comment by Macleykun** [comment]
Public nadeko on discord, hosted by kwoth
No need to find Kuro there. He can respond here when he has time.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: katherynliza <notifications@github.com>
Verzonden: vrijdag, augustus 9, 2019 10:58 PM
Aan: ScarletKuro/NadekoBot-Heroku-Auto-Deploy
CC: Macley; Comment
Onderwerp: Re: [ScarletKuro/NadekoBot-Heroku-Auto-Deploy] Music with no titles (#3)


Do you mean nadeko discord? Also there alot of Kuros on their discord

―

**Comment by ArgentBlueKitsune** [comment]
Already did that then, I was told to ask here since they dont deal with Heroku.

**Comment by Macleykun** [comment]
Wait for kuro to respond here then. Hope he finds the issue for ya! Gl

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: katherynliza <notifications@github.com>
Verzonden: vrijdag, augustus 9, 2019 11:02 PM
Aan: ScarletKuro/NadekoBot-Heroku-Auto-Deploy
CC: Macley; Comment
Onderwerp: Re: [ScarletKuro/NadekoBot-Heroku-Auto-Deploy] Music with no titles (#3)


Already did that then

**Comment by ScarletKuro** [comment]
I think that should be reported here https://gitlab.com/Kwoth/nadekobot
since I havent touched the original music module and doesn't rely on db modifications. Maybe redeploying youtube-dl dependecy on heroku can also help.

**Comment by ArgentBlueKitsune** [comment]
I did redeploy it and that did not fix the problem. 

Also if that is official Nadeko bot, they will not respond to any complaints once someone puts on heroku. 
Also, the bot hosted on my own computer is fine.

**Comment by ScarletKuro** [comment]
I really have no clue, since I can't reproduce it. I tried on my bot and seems ok. Installed the latest youtube-dl and bot build.
![sgfdsg](https://user-images.githubusercontent.com/19953225/62885641-0c198100-bd42-11e9-8ed5-7fcd2ac32e89.png)
Did you tried to redploy with cleaning the buildcache? https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

**Comment by katherynliza** [comment]
![image](https://user-images.githubusercontent.com/12589062/63111006-b10ea680-bf5a-11e9-86b5-2afd2d0e6028.png)

Sorry for such long response. I got the error above.

**Comment by ArgentBlueKitsune** [comment]
![image](https://user-images.githubusercontent.com/12589062/63111834-93dad780-bf5c-11e9-9aa6-dfec2cd6e7e4.png)

Before this I just ran auto-deploy, so I have none of the files locally.

**Comment by ScarletKuro** [comment]
oh, you have to do it localy. First you need Heroku CLI and git if you don't have it. Then you need to clone your heroku repository via `heroku git:clone -a appname`. If you don't have files inside for some reasons in the folder, then get it from here. If you had no files deploy them first
```
$ git add .
$ git commit -am "deploy"
$ git push heroku master
```
and then do the purge thing.
If it's too complicated I can do it for you, dm me on discord Kuro#5002 and i will explain how to give access to your bot.

**Comment by ScarletKuro** [comment]
solved
